// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WebhookGateway.API.Persistence;

#nullable disable

namespace WebhookGateway.API.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("WebhookGateway.API.WebhookEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("ReceivedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("WebhookEvents");
                });

            modelBuilder.Entity("WebhookGateway.API.WebhookEvent", b =>
                {
                    b.OwnsOne("WebhookGateway.API.WebhookEventMetadata", "Metadata", b1 =>
                        {
                            b1.Property<Guid>("WebhookEventId")
                                .HasColumnType("uuid");

                            b1.Property<string>("DeliveryId")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("DeliveryId");

                            b1.Property<string>("EventType")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("EventType");

                            b1.Property<string>("Provider")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("Provider");

                            b1.HasKey("WebhookEventId");

                            b1.HasIndex("Provider", "DeliveryId")
                                .IsUnique();

                            b1.ToTable("WebhookEvents");

                            b1.WithOwner()
                                .HasForeignKey("WebhookEventId");
                        });

                    b.Navigation("Metadata")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
